# Add Common Services operator source if APIs are not already present
{{- if not (.Capabilities.APIVersions.Has "operator.ibm.com/v1alpha1") }}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: IBMCS Operators
  publisher: IBM
  sourceType: grpc
  image: docker.io/opencloudio/ibm-common-service-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
{{- end }}
